### ISSUE TITLE
Semarang graphic display issue

### ISSUE THREAD

**Issue by fadmastuti** [urbanriskmap/cognicity-rem-v3#48] opened 2018-11-22 04:25 UTC
graphic display color seems inconsistance. 
action: coloring the RW map on 4 different flood criterias (red, orange, yellow, purple).
REM editing shows:

<img width="1434" alt="screen shot 2018-11-22 at 11 27 03 am" src="https://user-images.githubusercontent.com/2441950/48881739-91be6f00-ee49-11e8-84c4-eefd431aedd9.png">

public map shows:

<img width="1439" alt="screen shot 2018-11-22 at 11 21 57 am" src="https://user-images.githubusercontent.com/2441950/48881657-39876d00-ee49-11e8-8a71-b86fdce7cc0f.png">

both using dev version

**Comment by fadmastuti** [comment] 2018-11-27 04:25
it's back to purple now:

<img width="1439" alt="screen shot 2018-11-27 at 11 23 40 am" src="https://user-images.githubusercontent.com/2441950/49058534-f9543000-f236-11e8-87fe-d4c9e02024cc.png">

**Comment by matthewberryman** [comment] 2018-11-27 04:37
I can't reproduce in Chrome (cached, or in cognito mode with fresh cache) nor in Firefox. So given that plus @fadmastuti's latest update I'm closing this for now. Please feel free to re-open if for some reason it does reoccur.

**Closed as completed by matthewberryman** 2018-11-27 04:37 UTC
Labels: bug
