### ISSUE TITLE
First login on new browser doesn't let user update flood state

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-rem-v3#12] opened 2017-01-15 03:46 UTC
Trying to edit flood state returns an authentication error (403?)
- this only happens when first logging in on a new browser.

**Comment by matthewberryman** [comment] 2017-01-15 07:40
@talltom, if you were seeing this on rem-dev, it's possible that it was due to the cloudfront distribution for rem-dev not being set up properly, but it is now. If it was just on rem-dev then can you please test and see if that's fixed it? If not, I suspect the problem is with auth0 handling.

**Comment by matthewberryman** [comment] 2017-01-15 08:12
Have tested twice, can't reproduce, closing.

**Comment by matthewberryman** [comment] 2017-01-15 10:10
I'm still seeing this on the odd occasion

**Comment by tomasholderness** [comment] 2017-01-15 15:27
Can now reproduce consistently.
Steps to reproduce:
1. Open private/incognito window and login to REM (e.g. localhost, or dev or prod)
2. Attempt to edit a flood state
- results in `PUT https://data-dev.petabencana.id/floods/509?username=myusername@email.com 401 (Unauthorized)`
3. Refresh the page 
4. Resulting edits work

**Comment by tomasholderness** [comment] 2017-01-15 15:37
Update:- before refresh the Authorization token is not set in the header.
<img width="1114" alt="screen shot 2017-01-15 at 10 35 08 am" src="https://cloud.githubusercontent.com/assets/944642/21963802/849beb4a-db0e-11e6-8279-e26b4f7a4800.png">

`const auth = { headers: { 'Authorization': 'Bearer ' + localStorage.getItem('id_token') } };` is initialized on page load, but is not updated after login.

Time to make ☕...

**Comment by tomasholderness** [comment] 2017-01-15 16:01
@matthewberryman Pushed this fix to dev and seems to be working well. You've made a change and then a revert in dev which aren't in master - wanted to confirm you're happy to merge these updates (specifically:  a8785a5f03fb2f7a9eaed6f5c18fe0b1a0de3a4b and 29cea243338112027bc6a90b53cc109712947eed) before we push to prod? I assume because you've reverted we're all good, but thought best to double check.

**Comment by matthewberryman** [comment] 2017-01-15 17:23
@talltom Yes all good for you to merge.

**Closed as completed** 2017-01-16 00:53 UTC
Labels: bug
